//
//  CoinNameMapping.swift
//  CryptoSage
//
//  Provides proper display names for coins from exchanges like Binance
//  that may not have metadata from CoinGecko.
//

import Foundation

/// Static mapping of ticker symbols to proper display names and CoinGecko IDs
enum CoinNameMapping {
    
    /// Returns the proper display name for a symbol
    static func name(for symbol: String) -> String {
        let upper = symbol.uppercased()
        return symbolToName[upper] ?? formatSymbolAsName(upper)
    }
    
    /// Returns the CoinGecko ID for a symbol (if known)
    static func geckoID(for symbol: String) -> String {
        let upper = symbol.uppercased()
        return symbolToGeckoID[upper] ?? symbol.lowercased()
    }
    
    /// Returns the image URL for a symbol (if we have a known mapping)
    static func imageURL(for symbol: String) -> URL? {
        let geckoId = geckoID(for: symbol)
        // Use CoinGecko's standard image URL pattern
        return URL(string: "https://assets.coingecko.com/coins/images/\(geckoId)/small/\(geckoId).png")
    }
    
    /// Format symbol as a capitalized name (fallback)
    private static func formatSymbolAsName(_ symbol: String) -> String {
        // Handle common patterns
        if symbol.count <= 4 {
            return symbol // Short symbols look fine as-is
        }
        // For longer symbols, try to make them readable
        return symbol.capitalized
    }
    
    // MARK: - Symbol to Name Mapping
    
    private static let symbolToName: [String: String] = [
        // Top 100 by market cap
        "BTC": "Bitcoin",
        "ETH": "Ethereum",
        "USDT": "Tether",
        "BNB": "BNB",
        "SOL": "Solana",
        "USDC": "USD Coin",
        "XRP": "XRP",
        "DOGE": "Dogecoin",
        "ADA": "Cardano",
        "TRX": "TRON",
        "TON": "Toncoin",
        "SHIB": "Shiba Inu",
        "AVAX": "Avalanche",
        "LINK": "Chainlink",
        "DOT": "Polkadot",
        "BCH": "Bitcoin Cash",
        "NEAR": "NEAR Protocol",
        "LTC": "Litecoin",
        "MATIC": "Polygon",
        "UNI": "Uniswap",
        "ICP": "Internet Computer",
        "APT": "Aptos",
        "ETC": "Ethereum Classic",
        "ATOM": "Cosmos",
        "XLM": "Stellar",
        "FIL": "Filecoin",
        "HBAR": "Hedera",
        "ARB": "Arbitrum",
        "OP": "Optimism",
        "SUI": "Sui",
        "IMX": "Immutable",
        "RNDR": "Render",
        "INJ": "Injective",
        "VET": "VeChain",
        "GRT": "The Graph",
        "ALGO": "Algorand",
        "FTM": "Fantom",
        "AAVE": "Aave",
        "THETA": "Theta Network",
        "MKR": "Maker",
        "XTZ": "Tezos",
        "EOS": "EOS",
        "FLOW": "Flow",
        "SAND": "The Sandbox",
        "AXS": "Axie Infinity",
        "MANA": "Decentraland",
        "CHZ": "Chiliz",
        "NEO": "NEO",
        "QNT": "Quant",
        "EGLD": "MultiversX",
        "KCS": "KuCoin Token",
        "TIA": "Celestia",
        "SEI": "Sei",
        "STX": "Stacks",
        "GALA": "Gala",
        "CAKE": "PancakeSwap",
        "CRV": "Curve DAO",
        "SNX": "Synthetix",
        "LDO": "Lido DAO",
        "RUNE": "THORChain",
        "ENS": "Ethereum Name Service",
        "KAVA": "Kava",
        "RPL": "Rocket Pool",
        "ROSE": "Oasis Network",
        "ZIL": "Zilliqa",
        "MINA": "Mina",
        "ONE": "Harmony",
        "GMT": "STEPN",
        "ENJ": "Enjin Coin",
        "1INCH": "1inch",
        "MASK": "Mask Network",
        "BAT": "Basic Attention Token",
        "YFI": "yearn.finance",
        "COMP": "Compound",
        "BLUR": "Blur",
        "DYDX": "dYdX",
        "SUSHI": "SushiSwap",
        "ANKR": "Ankr",
        "ZRX": "0x Protocol",
        "CELO": "Celo",
        "AUDIO": "Audius",
        "STORJ": "Storj",
        "SKL": "SKALE",
        "ICX": "ICON",
        "OMG": "OMG Network",
        "OCEAN": "Ocean Protocol",
        "CELR": "Celer Network",
        "RLC": "iExec RLC",
        "NKN": "NKN",
        "CTSI": "Cartesi",
        "BAND": "Band Protocol",
        "RSR": "Reserve Rights",
        "FET": "Fetch.ai",
        "AGIX": "SingularityNET",
        "GLM": "Golem",
        "JASMY": "JasmyCoin",
        "HNT": "Helium",
        "KSM": "Kusama",
        "IOTA": "IOTA",
        "ZEC": "Zcash",
        "WAVES": "Waves",
        "XEM": "NEM",
        "DCR": "Decred",
        "SC": "Siacoin",
        "QTUM": "Qtum",
        "RVN": "Ravencoin",
        "ONT": "Ontology",
        "HOT": "Holo",
        "SXP": "Solar",
        "WOO": "WOO",
        "PEOPLE": "ConstitutionDAO",
        "LUNC": "Terra Classic",
        "FLOKI": "Floki",
        "BONK": "Bonk",
        "WIF": "dogwifhat",
        "PEPE": "Pepe",
        "ORDI": "ORDI",
        "JUP": "Jupiter",
        "PYTH": "Pyth Network",
        "JTO": "Jito",
        "STRK": "Starknet",
        "PIXEL": "Pixels",
        "MEME": "Memecoin",
        "AI16Z": "ai16z",
        "TRUMP": "TRUMP",
        "MELANIA": "Melania Meme",
        "FARTCOIN": "Fartcoin",
        "PNUT": "Peanut the Squirrel",
        "ACT": "Act I: The AI Prophecy",
        "VIRTUAL": "Virtuals Protocol",
        "ZEREBRO": "Zerebro",
        "GRIFFAIN": "Griffain",
        "GOAT": "Goatseus Maximus",
        "ARC": "AI Rig Complex",
        "SWARMS": "Swarms",
        "AIXBT": "aixbt",
        "ELIZA": "Eliza",
        "DEGEN": "Degen",
        "PENGU": "Pudgy Penguins",
        "TAO": "Bittensor",
        "KAS": "Kaspa",
        "RAY": "Raydium",
        "ORCA": "Orca",
        "MSOL": "Marinade Staked SOL",
        "JITOSOL": "Jito Staked SOL",
        "BNSOL": "Binance Staked SOL",
        "WBTC": "Wrapped Bitcoin",
        "WETH": "Wrapped Ethereum",
        "STETH": "Lido Staked ETH",
        "WSTETH": "Wrapped stETH",
        "CBETH": "Coinbase Wrapped Staked ETH",
        "RETH": "Rocket Pool ETH",
        "FRXETH": "Frax Ether",
        "EIGEN": "EigenLayer",
        "ETHFI": "ether.fi",
        "PENDLE": "Pendle",
        "ENA": "Ethena",
        "ONDO": "Ondo Finance",
        "HYPE": "Hyperliquid",
        "ME": "Magic Eden",
        "MOVE": "Movement",
        "USUAL": "Usual",
        "BIO": "BIO Protocol",
        "ZORA": "Zora",
        "AO": "AO",
        "GRASS": "Grass",
        "SPX": "SPX6900",
        "MOG": "Mog Coin",
        "BRETT": "Brett",
        "POPCAT": "Popcat",
        "NEIRO": "First Neiro On Ethereum",
        "AERO": "Aerodrome Finance",
    ]
    
    // MARK: - Symbol to CoinGecko ID Mapping
    
    private static let symbolToGeckoID: [String: String] = [
        "BTC": "bitcoin",
        "ETH": "ethereum",
        "USDT": "tether",
        "BNB": "binancecoin",
        "SOL": "solana",
        "USDC": "usd-coin",
        "XRP": "ripple",
        "DOGE": "dogecoin",
        "ADA": "cardano",
        "TRX": "tron",
        "TON": "the-open-network",
        "SHIB": "shiba-inu",
        "AVAX": "avalanche-2",
        "LINK": "chainlink",
        "DOT": "polkadot",
        "BCH": "bitcoin-cash",
        "NEAR": "near",
        "LTC": "litecoin",
        "MATIC": "matic-network",
        "UNI": "uniswap",
        "ICP": "internet-computer",
        "APT": "aptos",
        "ETC": "ethereum-classic",
        "ATOM": "cosmos",
        "XLM": "stellar",
        "FIL": "filecoin",
        "HBAR": "hedera",
        "ARB": "arbitrum",
        "OP": "optimism",
        "SUI": "sui",
        "IMX": "immutable-x",
        "RNDR": "render-token",
        "INJ": "injective-protocol",
        "VET": "vechain",
        "GRT": "the-graph",
        "ALGO": "algorand",
        "FTM": "fantom",
        "AAVE": "aave",
        "THETA": "theta-token",
        "MKR": "maker",
        "XTZ": "tezos",
        "EOS": "eos",
        "FLOW": "flow",
        "SAND": "the-sandbox",
        "AXS": "axie-infinity",
        "MANA": "decentraland",
        "CHZ": "chiliz",
        "NEO": "neo",
        "QNT": "quant-network",
        "EGLD": "elrond-erd-2",
        "TIA": "celestia",
        "SEI": "sei-network",
        "STX": "blockstack",
        "GALA": "gala",
        "CAKE": "pancakeswap-token",
        "CRV": "curve-dao-token",
        "SNX": "synthetix-network-token",
        "LDO": "lido-dao",
        "RUNE": "thorchain",
        "ENS": "ethereum-name-service",
        "KAVA": "kava",
        "RPL": "rocket-pool",
        "MINA": "mina-protocol",
        "TAO": "bittensor",
        "KAS": "kaspa",
        "PEPE": "pepe",
        "BONK": "bonk",
        "WIF": "dogwifcoin",
        "FLOKI": "floki",
        "ORDI": "ordi",
        "JUP": "jupiter-exchange-solana",
        "PYTH": "pyth-network",
        "HYPE": "hyperliquid",
        "PENGU": "pudgy-penguins",
        "VIRTUAL": "virtual-protocol",
        "FARTCOIN": "fartcoin",
        "AI16Z": "ai16z",
        "GOAT": "goatseus-maximus",
        "WBTC": "wrapped-bitcoin",
        "STETH": "staked-ether",
        "EIGEN": "eigenlayer",
        "ENA": "ethena",
        "ONDO": "ondo-finance",
        "PENDLE": "pendle",
    ]
}
